const quotes = [
  '“Absolutely every single one of my actions is inte…ull of mindless action, you act without thought.”',
  '“The temporary satisfaction of quitting is outweighed by the eternal suffering of being a nobody.”',
  '“Find a person who is as successful as you’d like to be, ask them what to do, do it and work hard.”',
  '“Close your eyes. Focus on making yourself feel ex…ul. Imagine yourself destroying goals with ease.”',
  '“You can become rich, you can become strong, you c…es and enjoy the fact it will be very difficult.”',
  '“Your mind must be stronger than your feelings.”',
  '“Success is always stressful.”',
  '“Freedom will only come when you no longer trade your time for money.”',
  '“Cost is the enemy of the poor man, so the poor tr…y of the rich man, so the rich try to save time.”',
  '“You must put in the effort to get the life you want.”',
  '“Arrogance breeds complacency and complacency breeds failure.”',
  '“Do the impossible and you’ll never doubt yourself ever again.”',
  '“You are exactly where you deserve to be. Change who you are and you will change how you live.”',
  '“The internet is the new battleground of earth, the wild west, the place of truth and opportunity.”',
  '“Arrogance is the cause of most first world poverty.”',
  '“Today you can act as an amateur or you can be a professional. Decide what you will do right now.”',
  '“Emotional control isn’t a lack of emotion; it’s a necessary function of maturity.”',
  '“Intellect is nothing without energy. Ideas are nothing without energy. High energy people win.”',
  '“High standards protect you from low-quality experiences.”',
  '“Aspire to be a superhero. Not a normal person with a bigger house and nicer car.”',
  '“The man who goes to the gym every single day rega… to the gym when he feels like going to the gym.”',
  '“The amount of stress you can tolerate while remai…rrelated to the level of success you will enjoy.”',
  '“There is no joy without pain.”',
  '“Don’t listen to the advice of people who are living lives you don’t want to live.”',
  '“You are never going to have any of the things you… Nobody cares about you enough to do it for you.”',
  "Don't look back your'e not going that way!"
];

module.exports = quotes;